version: "3.8"
services:
    code-server:
        build: .
        container_name: code-server
        volumes:
            - ./workspace:/config/workspace
            - ./config/xstartup:/config/.vnc/xstartup
            - ./config/settings.json:/config/data/settings.json
        ports:
            - 8080:8080
            - 5900:5900
            - 80:8443
            - 8000:8000
        restart: unless-stopped


